### ISSUE TITLE
R15 Vote Total Discrepancy on Notion

### ISSUE THREAD

**Issue by rbb36** [oceanprotocol/DAOBot#149]
**Describe the bug**
Upon looking at the Airtable data in oceandao.notion.site, I saw that my project (DeadmanDAO Web3 Hacker Network) had fewer reported "Yes" votes than I had cast for it. Since this seemed impossible, I dug deeper and found further discrepancies.

Additional detail, including data, here: https://wiki.deadmandao.com/index.php/OceanR15GrantPeculiarity

I believe it had no impact on the amount of OCEAN Granted, nor on the projects which received the grants, within [New Entrants]. I did not dig into the other grant categories, but my script did [provide totals](https://wiki.deadmandao.com/index.php/OceanR15GrantPeculiarity#Tabulated_Values).

**To Reproduce**
1. Go to https://oceandao.notion.site/Round-15-Votes-b2a854feaceb4393af3909684c065dbe
2. Look at the vote totals under New Entrants, look at the "Yes" total for DeadmanDAO Web3 Hacker Network, see 357.
3. Go to https://snapshot.org/#/officialoceandao.eth/proposal/QmYj1PtRV2hRw54Yjd1y5YBt3GgQmjTjyyLGRzhtweHUVZ
4. Find "0xAE6A...1931", with 515 votes, 95% cast for DeadmanDAO Web3 Hacker Network_Yes.
5. 515 * 0.95 = 489.25, which is greater than 357 displayed on Notion.
6. Find "mantisclone.eth", with 38k votes, 3.6% for DeadmanDAO Web3 Hacker Network_Yes.
7. 38,000 * 0.036 = 1368, which is also greater than the 357 displayed on Notion.
8. For more detail, go to: https://wiki.deadmandao.com/index.php/OceanR15GrantPeculiarity

**Expected behavior**
Totals shown on Notion should match the tabulated totals from snapshot.org.

**Screenshots**
No screenshots, but details here: https://wiki.deadmandao.com/index.php/OceanR15GrantPeculiarity

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 98.0

**Smartphone (please complete the following information):**
 - Device: Not Tested
 - OS: Not Tested
 - Browser Not Tested
 - Version Not Tested

**Additional context**

**Comment by idiom-bytes** [comment]
Hi @rbb36, thank you so much for looking into this and putting together such a well-written issue.

I believe if you were to look at it again, you would see that Airtable is now reporting the same amount as Snapshot.
Notion/Airtable - https://oceandao.notion.site/Round-15-Votes-b2a854feaceb4393af3909684c065dbe
Snapshot - https://vote.oceanprotocol.com/#/proposal/QmYj1PtRV2hRw54Yjd1y5YBt3GgQmjTjyyLGRzhtweHUVZ

calculateMatch() is the function you are looking for.
https://github.com/oceanprotocol/DAOBot/blob/96a8da1e455fd70731b4c73855ab158fdd2d394e/src/snapshot/snapshot_utils.js#L498

This update was released the very end of R15, in order to complete the distribution of funds, which you can find here:
https://docs.google.com/spreadsheets/d/1e4xb6m-aKcBhwob_p7ereSFneXFPpDjUbSjz13smmHI/edit#gid=1765938454

There were 235k OCEAN distributed, for a total of $100k USD.

Thank you.

**Comment by rbb36** [comment]
Alas - I'm still seeing the same "Yes" totals in both Firefox and Chromium. DeadmanDAO shows 357 Yes votes.

I also tried it with both DuckDuckGo browser and Chrome on my OnePlus Nord N200 cell phone. Same 357 votes.

![ocean-r15-peculiarity-chromium](https://user-images.githubusercontent.com/2435883/157369156-c08d68d9-6e7a-4131-9e5e-21e594cd66d5.png)
![ocean-r15-peculiarity-firefox](https://user-images.githubusercontent.com/2435883/157369160-60cfded8-ed04-4933-8780-5c80fe030441.png)

**Comment by rbb36** [comment]
Oh - interesting - Snapshot's summary data on the right does not match the sum of the individual rows on the left.

**Comment by rbb36** [comment]
Now I see why - it's using quadratic voting.
